### ISSUE TITLE
Support CSV format

### ISSUE THREAD

**Issue by pbeshai** [bocoup/mlab-vis-api#16]
**Goal:** Be able to specify data format in the URL, not just with HTTP headers, but setting it via HTTP headers should work too.

I've begun investigating getting the data in CSV format. I think I've hit a limitation in flask_restplus.

It will work fine if the `Accept` header is set to `text/csv` and you supply a function that converts model marshaled data to CSV via `@api.representation('text/csv')` For example:

```python
@api.representation('text/csv')
def csv_mediatype_representation(data, code, headers):
    resp = make_response(convert_to_csv(data), code)
    resp.headers.extend(headers)
    return resp
```

flask_restplus already comes with default support for `application/json`. 

This only becomes a problem when you want to have the data format specified by a URL parameter instead of an HTTP header. e.g. `/locations/nauswaseattle/metrics?timebin=month&format=csv`. The way flask_restplus is coded makes it so whatever the matched mediatype is, that is what the `Content-Type` header on the response will be set to. This means the best we could do is provide `Content-Type: text/plain` for all our responses and just have the content vary. Not ideal -- JSON data should come back with `Content-Type: application/json` and CSV data with `Content-Type: text/csv`. 

This is the chunk of code in flask_restplus that limits us: https://github.com/noirbizarre/flask-restplus/blob/master/flask_restplus/api.py#L337-L340. It sets the content type then the response is sent out via flask with no way to intercept. 

So it seems the only way to really support it is to use `Content-Type: text/plain` for everything. 

I did have another idea though: proxying different format requests. Basically instead of passing `format` as a query parameter, we would use it as part of the URL to match then do a proxy that sets the appropriate header. The problem we're trying to solve is having a URL that will return the data with the correct type when shared/put in a link tag. So you could have:

* `/locations/nauswaseattle/metrics?timebin=month` -- returns formatted based on `Accept` header (defaults to `application/json`)
* `/csv/locations/nauswaseattle/metrics?timebin=month` -- proxies a call to `/locations/nauswaseattle/metrics?timebin=month` with `Accept: text/csv`
* `/json/locations/nauswaseattle/metrics?timebin=month` -- proxies a call to `/locations/nauswaseattle/metrics?timebin=month` with `Accept: application/json` (not necessary, but for consistency)

Kind of ugly way to work around the limitation of the flask_restplus. Thoughts @vlandham?

----

**Update**

After @vlandham's suggestion, I have managed to get this working using a decorator applied to all resources of the API via restplus' `decorators` parameter. The following endpoints have been updated to support CSV:

### Locations
- [x] /locations/search
- [x] /locations/top
- [x] /locations/id/info
- [x] /locations/id/children
- [x] /locations/id/clients
- [x] /locations/id/servers
- [x] /locations/id/clients/id/info
- [x] /locations/id/metrics
- [x] /locations/id/clients/id/metrics
- [x] /locations/id/servers/id/metrics
- [x] /locations/id/clients/id/servers/id/metrics

### Clients
- [x] /clients/search
- [x] /clients/top
- [x] /clients/id/info
- [x] /clients/id/servers
- [x] /clients/id/locations
- [x] /clients/id/metrics
- [x] /clients/id/servers/id/metrics

### Servers
- [x] /servers/search
- [x] /servers/top
- [x] /servers/id/info
- [x] /servers/id/clients
- [x] /servers/id/locations
- [x] /servers/id/metrics

**Comment by pbeshai** [comment]
Initial work prior to thinking of proxying here: https://github.com/bocoup/mlab-vis-api/tree/csv-support

**Comment by vlandham** [comment]
I agree the url parameter is a somewhat ugly approach to this...

so what if we start with a header only approach - and get csv exporting going with the `Content-Type` set correctly. This maintains a ['restful']:(http://www.programmableweb.com/news/rest-api-design-put-type-content-type/2011/11/18) approach... and is easy to get started. 

I'm assuming the code at: https://github.com/noirbizarre/flask-restplus/blob/master/flask_restplus/api.py#L337-L340 

is run before any of our code is - so we couldn't re-write the `Content-Type` based on a parameter?

**Comment by pbeshai** [comment]
```python
        if mediatype in self.representations:
            resp = self.representations[mediatype](data, *args, **kwargs)
            resp.headers['Content-Type'] = mediatype
            return resp
```

- the self.representations line is what calls our code to transform the response to the desired type.
- return resp then goes directly to flask with no further ability to intercept, so we can't change the Content Type.

**Comment by pbeshai** [comment]
ok the problem with the header-only approach is that we can't make links work. One way around it is to have the links actually generate requests via ajax so we can set headers. The downside is if they "right click and open in new window" they will not have the desired encoding.
