### ISSUE TITLE
When deployed, turn off debug mode

### ISSUE THREAD

**Issue by pbeshai** [bocoup/mlab-vis-api#5]
Debug mode adds a bunch of whitespace to the JSON responses, which is undesired in production.

See `main.py`

```python
if __name__ == '__main__':
    app.run(port=8080, debug=True)
```

**Comment by tkellen** [comment]
If you're not using it already, this is great!
https://github.com/theskumar/python-dotenv

**Comment by vlandham** [comment]
done and done. now uses dotenv and defaults to production build.
